"use client"

import { useState } from "react"
import { useLiveQuery } from "dexie-react-hooks"
import { db } from "@/lib/db"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { formatCurrency } from "@/lib/currencies"
import { Trash2 } from "lucide-react"

export function AccountSettings(){const accounts=useLiveQuery(()=>db.accounts.toArray())||[];const[editing,setEditing]=useState<string|null>(null);const[value,setValue]=useState('');async function save(id:string){const amount=Number(value.replace(',','.'));if(!Number.isFinite(amount))return;await db.accounts.update(id,{currentBalanceMinor:Math.round(amount*100),balanceAsOf:new Date().toISOString().slice(0,10),updatedAt:new Date().toISOString()});setEditing(null);setValue('')}return <div className="border divide-y">{accounts.map(account=><div key={account.id} className="p-3"><div className="flex items-center justify-between gap-3"><div><p className="text-sm font-medium">{account.name}</p><p className="mt-1 text-xs text-muted-foreground">{account.institution} · {account.type.replace('_',' ')}{account.balanceAsOf?` · balance as of ${account.balanceAsOf}`:''}</p></div>{editing===account.id?<div className="flex gap-2"><Input className="w-28 mono" value={value} onChange={event=>setValue(event.target.value)} placeholder="0.00" autoFocus/><Button size="sm" onClick={()=>void save(account.id)}>Save</Button></div>:<button className="mono text-sm" onClick={()=>{setEditing(account.id);setValue(account.currentBalanceMinor==null?'':String(account.currentBalanceMinor/100))}}>{account.currentBalanceMinor==null?'Set balance':formatCurrency(account.currentBalanceMinor/100,account.currency)}</button>}</div></div>)}</div>}

export function MerchantRuleSettings(){const rules=useLiveQuery(()=>db.merchantRules.orderBy('priority').reverse().toArray())||[];if(!rules.length)return <div className="border border-dashed p-5 text-sm text-muted-foreground">Rules appear here after you correct an imported merchant category.</div>;return <div className="border divide-y">{rules.map(rule=><div key={rule.id} className="flex items-center justify-between p-3"><div><p className="text-sm font-medium">{rule.normalizedMerchant}</p><p className="mt-1 text-xs text-muted-foreground">{rule.matchType} match · learned from a correction</p></div><Button variant="ghost" size="icon" onClick={()=>void db.merchantRules.delete(rule.id)} aria-label={`Delete ${rule.normalizedMerchant} rule`}><Trash2 className="h-4 w-4"/></Button></div>)}</div>}

export function ImportHistory(){const imports=useLiveQuery(()=>db.imports.orderBy('importedAt').reverse().limit(20).toArray())||[];if(!imports.length)return <div className="border border-dashed p-5 text-sm text-muted-foreground">No statements imported yet.</div>;return <div className="border divide-y">{imports.map(item=><div key={item.id} className="flex items-center justify-between p-3 gap-4"><div className="min-w-0"><div className="flex items-center gap-2"><p className="truncate text-sm font-medium">{item.fileName}</p>{item.reconciled!==undefined&&<span className={`text-[10px] mono ${item.reconciled?'text-green-600':'text-amber-600'}`}>{item.reconciled?'RECONCILED':'CHECK TOTALS'}</span>}</div><p className="mt-1 text-xs text-muted-foreground">{item.source}{item.periodStart&&item.periodEnd?` · ${item.periodStart} – ${item.periodEnd}`:` · ${new Date(item.importedAt).toLocaleString()}`}{item.dueDate?` · due ${item.dueDate}`:''}</p></div><div className="text-right shrink-0"><p className="mono text-xs">{item.importedCount} new · {item.duplicateCount} skipped</p>{item.amountDueMinor!==undefined&&<p className="mt-1 text-xs text-muted-foreground">Due {formatCurrency(item.amountDueMinor/100,item.statementCurrency||'EUR')}</p>}</div></div>)}</div>}
